---
- name: add epel-release repo
  dnf:
    name: epel-release
    state: present

- name: update package list
  dnf:
    update_cache: true

- name: install certbot libs
  package:
    name: "{{ item }}"
    state: present
  loop:
    - certbot
    - python3-certbot-nginx

- name: setup cronjob to renew certs
  cron:
    name: renew lets-encrypt certificates
    minute: 0
    hour: 12
    job: /usr/bin/certbot renew > /var/log/certbot-cert-renewal.log