---
all:
  children:
    development:
      hosts:
        dev-app-1:
          ansible_host: dev.example.com
          ansible_user: root
          app_env: development

  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
