# Frontend service inventory configuration for development environment
# This file defines the configuration for React frontend services

all:
  hosts:
    app1:
      ansible_host: # IP address of the host  

  vars:
    role: frontend
    type: react
    repository: # Repository URL for the artifact  
    branch: main

    container_port: 80
    host_port: 8081
    container_name: frontend-app
    hostname: # Hostname of the server  

    health_check_path: /health
    health_check_port: 8081

    monitoring_enabled: true
    prometheus_port: 9090

    backup_enabled: true
    backup_schedule: "0 0 * * *" # Daily at midnight
